singleServerConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  password: null
  subscriptionsPerConnection: 5
  clientName: collapix-redis
  address: "redis://127.0.0.1:6390"
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 24
  connectionPoolSize: 64
  database: 1
  dnsMonitoringInterval: 5000
threads: 16
nettyThreads: 16
codec: !<org.redisson.codec.Kryo5Codec> {}
transportMode: "NIO"
lockWatchdogTimeout: 10000
reliableTopicWatchdogTimeout: 60000