
name: collapix
services:
  mysql:
    image: "mysql:8.4"
    container_name: mysql001
    ports:
      - "3306:3306"
    volumes:
      - /home/docker/volumns/mysql001:/var/lib/mysql
      - /home/docker/volumns/mysql001/conf:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass001
      - MYSQL_DATABASE=colla_pix
    networks:
      - app_network
    mem_limit: 1g
    restart: unless-stopped

  redis:
    image: "redis:7.4.2"
    container_name: redis001
    networks:
      - app_network
    ports:
      - "6390:6380"
    volumes:
      - /home/docker/volumns/redis001/data:/data
      - /home/docker/volumns/redis001/conf:/usr/local/etc/redis
      - /home/docker/volumns/redis001/log:/var/log/redis
    command: redis-server /usr/local/etc/redis/redis.conf
    mem_limit: 512m
    restart: unless-stopped

  collapix_app:
    depends_on:
      - mysql
      - redis
    image: "1347428036/esmiao:1.0.0"
    container_name: collapix_server
    networks:
      - app_network
    ports:
      - "8123:8123"
    mem_limit: 1g
    environment:
      JAVA_TOOL_OPTIONS: "-DSpring.profiles.active=prod -Dapp.cache.manager=multilayer -Dshardingsphere.datasource.collapix.jdbcUrl=jdbc:mysql://mysql001:3306/colla_pix?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai -Dshardingsphere.datasource.collapix.username=root -Dshardingsphere.datasource.collapix.password=rootpass001 -Dshardingsphere.showSql=true"
    restart: unless-stopped

networks:
  app_network:
    driver: bridge